import os
from dotenv import load_dotenv

### Beziehen der Umgebungsvariablen für den Datenbankzugriff ###
load_dotenv()

MARIADB_USERNAME = os.getenv('MARIADB_USERNAME')
MARIADB_PASSWORD = os.getenv('MARIADB_PASSWORD')
MARIADB_SERVERNAME = os.getenv('MARIADB_SERVERNAME')
MARIADB_PORTNUMBER = os.getenv('MARIADB_PORTNUMBER')
MARIADB_ENCODING = os.getenv('MARIADB_ENCODING')
POSTGRES_USERNAME = os.getenv('POSTGRES_USERNAME')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_SERVERNAME = os.getenv('POSTGRES_SERVERNAME')
POSTGRES_PORTNUMBER = os.getenv('POSTGRES_PORTNUMBER')
POSTGRES_ENCODING = os.getenv('POSTGRES_ENCODING')

environment_variables = {
    MARIADB_USERNAME,
    MARIADB_PASSWORD,
    MARIADB_SERVERNAME,
    MARIADB_PORTNUMBER,
    MARIADB_ENCODING,
    POSTGRES_USERNAME,
    POSTGRES_PASSWORD,
    POSTGRES_SERVERNAME,
    POSTGRES_PORTNUMBER,
    POSTGRES_ENCODING
}
